local-zone: "193.120.199.15" always_refuse
local-zone: "204.9.163.200" always_refuse
local-zone: "212.161.8.36" always_refuse
local-zone: "213.146.189.205" always_refuse
local-zone: "91.190.216.26" always_refuse
local-zone: "comtube.ru" always_refuse
local-zone: "ekiga.net" always_refuse
local-zone: "freecall.com" always_refuse
local-zone: "globe7.com" always_refuse
local-zone: "indafon.hu" always_refuse
local-zone: "instantaudio.com" always_refuse
local-zone: "internetcalls.com" always_refuse
local-zone: "jajah.com" always_refuse
local-zone: "justvoip.com" always_refuse
local-zone: "keyyo.com" always_refuse
local-zone: "keyyo.fr" always_refuse
local-zone: "lingo.com" always_refuse
local-zone: "livereceptionist.com" always_refuse
local-zone: "my.three.com.au" always_refuse
local-zone: "net2phone.com" always_refuse
local-zone: "NetAppel.com" always_refuse
local-zone: "netspeak.com" always_refuse
local-zone: "nimbuzz.com" always_refuse
local-zone: "pc080.net" always_refuse
local-zone: "pda.turbocall.com" always_refuse
local-zone: "peterzahlt.de" always_refuse
local-zone: "p-group.cc" always_refuse
local-zone: "poivy.com" always_refuse
local-zone: "relay.voice.messenger.msn.com" always_refuse
local-zone: "sipcall.ch" always_refuse
local-zone: "SIPDiscount.com" always_refuse
local-zone: "sipme.me" always_refuse
local-zone: "skype.com" always_refuse
local-zone: "skype.ekolay.net" always_refuse
local-zone: "skype.net" always_refuse
local-zone: "SparVoip.de" always_refuse
local-zone: "spreed.com" always_refuse
local-zone: "thepudding.com" always_refuse
local-zone: "toky.co" always_refuse
local-zone: "viber.com" always_refuse
local-zone: "viva.gr" always_refuse
local-zone: "voice2page.com" always_refuse
local-zone: "voice.yahoo.com" always_refuse
local-zone: "voipcheap.com" always_refuse
local-zone: "voipdiscount.com" always_refuse
local-zone: "voipraider.com" always_refuse
local-zone: "voipstunt.com" always_refuse
local-zone: "voip.uol.com.br" always_refuse
local-zone: "webcalldirect.com" always_refuse
local-zone: "webphone.com" always_refuse
local-zone: "wegwerfnummer.de" always_refuse
local-zone: "wengomeeting.com" always_refuse
local-zone: "wengophone.com" always_refuse
local-zone: "yoomba.com" always_refuse
