address=/193.120.199.15/0.0.0.0
address=/204.9.163.200/0.0.0.0
address=/212.161.8.36/0.0.0.0
address=/213.146.189.205/0.0.0.0
address=/91.190.216.26/0.0.0.0
address=/comtube.ru/0.0.0.0
address=/ekiga.net/0.0.0.0
address=/freecall.com/0.0.0.0
address=/globe7.com/0.0.0.0
address=/indafon.hu/0.0.0.0
address=/instantaudio.com/0.0.0.0
address=/internetcalls.com/0.0.0.0
address=/jajah.com/0.0.0.0
address=/justvoip.com/0.0.0.0
address=/keyyo.com/0.0.0.0
address=/keyyo.fr/0.0.0.0
address=/lingo.com/0.0.0.0
address=/livereceptionist.com/0.0.0.0
address=/my.three.com.au/0.0.0.0
address=/net2phone.com/0.0.0.0
address=/NetAppel.com/0.0.0.0
address=/netspeak.com/0.0.0.0
address=/nimbuzz.com/0.0.0.0
address=/pc080.net/0.0.0.0
address=/pda.turbocall.com/0.0.0.0
address=/peterzahlt.de/0.0.0.0
address=/p-group.cc/0.0.0.0
address=/poivy.com/0.0.0.0
address=/relay.voice.messenger.msn.com/0.0.0.0
address=/sipcall.ch/0.0.0.0
address=/SIPDiscount.com/0.0.0.0
address=/sipme.me/0.0.0.0
address=/skype.com/0.0.0.0
address=/skype.ekolay.net/0.0.0.0
address=/skype.net/0.0.0.0
address=/SparVoip.de/0.0.0.0
address=/spreed.com/0.0.0.0
address=/thepudding.com/0.0.0.0
address=/toky.co/0.0.0.0
address=/viber.com/0.0.0.0
address=/viva.gr/0.0.0.0
address=/voice2page.com/0.0.0.0
address=/voice.yahoo.com/0.0.0.0
address=/voipcheap.com/0.0.0.0
address=/voipdiscount.com/0.0.0.0
address=/voipraider.com/0.0.0.0
address=/voipstunt.com/0.0.0.0
address=/voip.uol.com.br/0.0.0.0
address=/webcalldirect.com/0.0.0.0
address=/webphone.com/0.0.0.0
address=/wegwerfnummer.de/0.0.0.0
address=/wengomeeting.com/0.0.0.0
address=/wengophone.com/0.0.0.0
address=/yoomba.com/0.0.0.0
